development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: alex.h.frey
  :password: back6688GM
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: xxx
  :password: yyy
  :enable_starttls_auto: true