development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: alex.h.frey
  :password: back6688GM
  :enable_starttls_auto: true
production:
  :address: smtp.sendgrid.net
  :port: 587
  :authentication: plain
  :user_name: franny
  :password: 8Chickens
  :enable_starttls_auto: true